ALTER TABLE public.stats_linea
DROP COLUMN IF EXISTS defaut_operateur_pieces,
DROP COLUMN IF EXISTS defaut_operateur_pourcentage,
DROP COLUMN IF EXISTS defaut_planar_pieces,
DROP COLUMN IF EXISTS defaut_planar_pourcentage,
DROP COLUMN IF EXISTS defaut_calibre_pieces,
DROP COLUMN IF EXISTS defaut_calibre_pourcentage;

ALTER TABLE public.stats_linea
ADD COLUMN IF NOT EXISTS choix1_operateur_pieces NUMERIC NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS choix1_operateur_pourcentage NUMERIC NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS choix1_planar_pieces NUMERIC NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS choix1_planar_pourcentage NUMERIC NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS choix1_calibre_pieces NUMERIC NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS choix1_calibre_pourcentage NUMERIC NOT NULL DEFAULT 0,

ADD COLUMN IF NOT EXISTS choix2_operateur_pieces NUMERIC NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS choix2_operateur_pourcentage NUMERIC NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS choix2_planar_pieces NUMERIC NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS choix2_planar_pourcentage NUMERIC NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS choix2_calibre_pieces NUMERIC NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS choix2_calibre_pourcentage NUMERIC NOT NULL DEFAULT 0,

ADD COLUMN IF NOT EXISTS choix3_operateur_pieces NUMERIC NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS choix3_operateur_pourcentage NUMERIC NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS choix3_planar_pieces NUMERIC NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS choix3_planar_pourcentage NUMERIC NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS choix3_calibre_pieces NUMERIC NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS choix3_calibre_pourcentage NUMERIC NOT NULL DEFAULT 0;

