-- Add missing columns to interventions table
ALTER TABLE public.interventions 
ADD COLUMN IF NOT EXISTS numero TEXT,
ADD COLUMN IF NOT EXISTS date_intervention DATE,
ADD COLUMN IF NOT EXISTS heure_demande TIME,
ADD COLUMN IF NOT EXISTS equipe TEXT,
ADD COLUMN IF NOT EXISTS visa_demandeur TEXT,
ADD COLUMN IF NOT EXISTS intervenants JSONB DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS arret_cpmp NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS arret_cpr NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS arret_cle NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS arret_ccu NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS arret_csl NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS total_arret NUMERIC DEFAULT 0;
