// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://brbrlbhmwpekdipwfxci.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJyYnJsYmhtd3Bla2RpcHdmeGNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIyNjc0NTAsImV4cCI6MjA4Nzg0MzQ1MH0.u0K8GF15zbpMjbUurQDvvepOfH9IBS8ugjmJAHgk-Ys";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
